[package]
name = "camigo-helpers-tests"
version = "0.0.1"
edition = "2018"

[dependencies]
camigo = { path = "../camigo" }
camigo-helpers = { path = "../camigo-helpers" }

[[test]]
name = "module-based-tests"
path = "src/tests.rs"

[lints.rust]
warnings = "allow"
